<?php

namespace Database\Seeders;

use App\Models\Language;
use Illuminate\Database\Seeder;

class LanguageLabelsSeeder extends Seeder
{
    public function run(): void
    {
        $labelDefaults = [
            'en' => [
                'basic_info' => 'Basic Information',
                'card_title' => 'Card Title *',
                'subtitle' => 'Subtitle',
                'theme' => 'Theme',
                'primary_lang' => 'Primary Language',
                'card_sections' => 'Card Sections',
                'save_sections' => 'Save Sections',
                'saving' => 'Saving...',
                'publishing' => 'Publishing',
                'status' => 'Status',
                'published' => 'Published',
                'draft' => 'Draft',
                'publish' => 'Publish',
                'unpublish' => 'Unpublish',
                'stats' => 'Statistics',
                'views' => 'Views',
                'shares' => 'Shares',
                'share' => 'Share',
                'public_url' => 'Public URL',
                'copy' => 'Copy',
                'cover_image' => 'Cover Image',
                'profile_image' => 'Avatar / Logo',
                'ai_translation' => 'AI Translation',
                'translation_credits' => 'Translation Credits',
                'translate_to' => 'Translate to Languages',
                'translate_card' => 'Translate Entire Card',
                'translating' => 'Translating...',
                'translation_info' => 'Will translate card + all sections to :count language(s)',
                'no_credits' => 'You\'ve used all your translation credits for this month.',
                'upgrade_plan' => 'Upgrade Plan',
                'section' => 'Section',
                'remove' => 'Remove',
                'type' => 'Type',
                'content' => 'Content',
                'add_section' => 'Add Section',
                'placeholder' => 'Enter content in',
                'text' => 'Text',
                'image' => 'Image',
                'video' => 'Video',
                'link' => 'Link',
                'qr_code' => 'QR Code',
                'contact' => 'Contact Info',
                'social' => 'Social Links',
                'services' => 'Services',
                'products' => 'Products',
                'testimonials' => 'Testimonials',
                'hours' => 'Business Hours',
                'appointments' => 'Appointments',
                'gallery' => 'Gallery',
                'email' => 'Email',
                'phone' => 'Phone',
                'address' => 'Address',
                'website' => 'Website',
                'booking_url' => 'Booking URL',
                'instructions' => 'Instructions',
                'name' => 'Name',
                'description' => 'Description',
                'price' => 'Price',
                'quote' => 'Quote',
                'author' => 'Author',
                'company' => 'Company',
                'url' => 'URL',
                'caption' => 'Caption',
                'add_item' => 'Add Item',
            ],
            'ar' => [
                'basic_info' => 'المعلومات الأساسية',
                'card_title' => 'عنوان البطاقة *',
                'subtitle' => 'العنوان الفرعي',
                'theme' => 'القالب',
                'primary_lang' => 'اللغة الأساسية',
                'card_sections' => 'أقسام البطاقة',
                'save_sections' => 'حفظ الأقسام',
                'saving' => 'جاري الحفظ...',
                'publishing' => 'النشر',
                'status' => 'الحالة',
                'published' => 'منشور',
                'draft' => 'مسودة',
                'publish' => 'نشر',
                'unpublish' => 'إلغاء النشر',
                'stats' => 'الإحصائيات',
                'views' => 'المشاهدات',
                'shares' => 'المشاركات',
                'share' => 'مشاركة',
                'public_url' => 'الرابط العام',
                'copy' => 'نسخ',
                'cover_image' => 'صورة الغلاف',
                'profile_image' => 'الصورة الشخصية / الشعار',
                'ai_translation' => 'الترجمة بالذكاء الاصطناعي',
                'translation_credits' => 'رصيد الترجمة',
                'translate_to' => 'ترجمة إلى اللغات',
                'translate_card' => 'ترجمة البطاقة بالكامل',
                'translating' => 'جاري الترجمة...',
                'translation_info' => 'سيتم ترجمة البطاقة وجميع الأقسام إلى :count لغة',
                'no_credits' => 'لقد استخدمت جميع أرصدة الترجمة لهذا الشهر.',
                'upgrade_plan' => 'ترقية الخطة',
                'section' => 'قسم',
                'remove' => 'إزالة',
                'type' => 'النوع',
                'content' => 'المحتوى',
                'add_section' => 'إضافة قسم',
                'placeholder' => 'أدخل المحتوى بـ',
                'text' => 'نص',
                'image' => 'صورة',
                'video' => 'فيديو',
                'link' => 'رابط',
                'qr_code' => 'رمز QR',
                'contact' => 'معلومات الاتصال',
                'social' => 'روابط التواصل',
                'services' => 'الخدمات',
                'products' => 'المنتجات',
                'testimonials' => 'التوصيات',
                'hours' => 'ساعات العمل',
                'appointments' => 'المواعيد',
                'gallery' => 'معرض الصور',
                'email' => 'البريد الإلكتروني',
                'phone' => 'الهاتف',
                'address' => 'العنوان',
                'website' => 'الموقع الإلكتروني',
                'booking_url' => 'رابط الحجز',
                'instructions' => 'تعليمات',
                'name' => 'الاسم',
                'description' => 'الوصف',
                'price' => 'السعر',
                'quote' => 'الاقتباس',
                'author' => 'المؤلف',
                'company' => 'الشركة',
                'url' => 'الرابط',
                'caption' => 'الوصف',
                'add_item' => 'إضافة عنصر',
            ],
        ];

        foreach ($labelDefaults as $code => $labels) {
            Language::where('code', $code)->update(['labels' => $labels]);
        }
    }
}
