<?php

namespace App\Filament\Resources\TranslationHistoryResource\Pages;

use App\Filament\Resources\TranslationHistoryResource;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;

class ListTranslationHistories extends ListRecords
{
    protected static string $resource = TranslationHistoryResource::class;

    protected function getHeaderActions(): array
    {
        return [
            // No create action since translations are generated by AI
        ];
    }
}
